import fs from "node:fs";
import path from "node:path";
import { getPaths } from "./paths.js";
import type { Profile } from "./profiles.js";
import { loadProfiles } from "./profiles.js";

const HEADER = `# Auto-generated by claudex. Do not edit by hand — run 'claudex add/remove' instead.
# Each function loads its profile's .env (key inside) and runs the real \`claude\` binary
# with the right CLAUDE_CONFIG_DIR + ANTHROPIC_BASE_URL + model env vars.
`;

function escapeShell(value: string): string {
  // wrap in double quotes, escape internal $ \` \\ "
  return `"${value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\$/g, "\\$")
    .replace(/`/g, "\\`")}"`;
}

function aliasFunction(p: Profile): string {
  const { profilesDir } = getPaths();
  const dir = path.join(profilesDir, p.name);
  const fnName = `__claudex_run_${p.name.replace(/-/g, "_")}`;
  const lines: string[] = [];
  lines.push(`${fnName}() {`);
  lines.push(`  local profile_dir=${escapeShell(dir)}`);
  lines.push(`  if [ -f "$profile_dir/.env" ]; then`);
  lines.push(`    set -a`);
  lines.push(`    . "$profile_dir/.env"`);
  lines.push(`    set +a`);
  lines.push(`  fi`);
  // Build env preamble. CLAUDE_CONFIG_DIR is always set.
  const envLines: string[] = [`CLAUDE_CONFIG_DIR=${escapeShell(dir)}`];
  if (p.baseUrl) {
    envLines.push(`ANTHROPIC_BASE_URL=${escapeShell(p.baseUrl)}`);
    envLines.push(`ANTHROPIC_AUTH_TOKEN="\${CLAUDEX_KEY:-}"`);
    // For OpenRouter passthrough, ANTHROPIC_API_KEY must be empty so SDK
    // uses the AUTH_TOKEN path. Set it explicitly empty for safety.
    envLines.push(`ANTHROPIC_API_KEY=""`);
  }
  if (p.mainModel) envLines.push(`ANTHROPIC_MODEL=${escapeShell(p.mainModel)}`);
  if (p.smallModel)
    envLines.push(`ANTHROPIC_SMALL_FAST_MODEL=${escapeShell(p.smallModel)}`);
  lines.push(`  ${envLines.join(" \\\n  ")} \\`);
  lines.push(`    command claude "$@"`);
  lines.push(`}`);
  lines.push(`alias ${p.name}='${fnName}'`);
  return lines.join("\n");
}

export function regenerateAliases(): string {
  const { generatedDir, aliasesFile } = getPaths();
  fs.mkdirSync(generatedDir, { recursive: true });
  const profiles = loadProfiles();
  const body = profiles.map(aliasFunction).join("\n\n");
  const content = `${HEADER}\n${body}\n`;
  fs.writeFileSync(aliasesFile, content, { mode: 0o644 });
  return aliasesFile;
}
