import fs from "node:fs";
import path from "node:path";

const ENV_VAR = "CLAUDEX_KEY";

export function writeSecret(profileDir: string, key: string): void {
  fs.mkdirSync(profileDir, { recursive: true });
  const envPath = path.join(profileDir, ".env");
  const content = `# Generated by claudex. DO NOT commit.\n${ENV_VAR}=${escape(key)}\n`;
  fs.writeFileSync(envPath, content, { mode: 0o600 });
  try {
    fs.chmodSync(envPath, 0o600);
  } catch {
    // best-effort on platforms that don't support chmod
  }
}

export function readSecret(profileDir: string): string | null {
  const envPath = path.join(profileDir, ".env");
  try {
    const content = fs.readFileSync(envPath, "utf8");
    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eq = trimmed.indexOf("=");
      if (eq === -1) continue;
      const k = trimmed.slice(0, eq).trim();
      if (k !== ENV_VAR) continue;
      return unescape(trimmed.slice(eq + 1).trim());
    }
    return null;
  } catch {
    return null;
  }
}

export function hasSecret(profileDir: string): boolean {
  const envPath = path.join(profileDir, ".env");
  return fs.existsSync(envPath);
}

function escape(s: string): string {
  // double-quote and escape internal quotes/backslashes for safe shell sourcing
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$").replace(/`/g, "\\`")}"`;
}

function unescape(s: string): string {
  let trimmed = s;
  if (
    (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    trimmed = trimmed.slice(1, -1);
  }
  return trimmed
    .replace(/\\"/g, '"')
    .replace(/\\\$/g, "$")
    .replace(/\\`/g, "`")
    .replace(/\\\\/g, "\\");
}

export { ENV_VAR };
